examples/coffeeratings/config/routes.rb
Coffeeratings::Application.routes.draw do
  resources :roasters

  resources :espresso_machine_manufacturers

end

examples/coffeeratings/app/models/espresso_machine_manufacturer.rb
class EspressoMachineManufacturer < ActiveRecord::Base
  attr_accessible :groups, :machine_types, :models, :name, :website
end

examples/coffeeratings/app/models/roaster.rb
class Roaster < ActiveRecord::Base
  attr_accessible :blends, :name, :website
end

examples/coffeeratings/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

examples/coffeeratings/app/controllers/espresso_machine_manufacturers_controller.rb
class EspressoMachineManufacturersController < ApplicationController
  # GET /espresso_machine_manufacturers
  # GET /espresso_machine_manufacturers.json
  def index
    @espresso_machine_manufacturers = EspressoMachineManufacturer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @espresso_machine_manufacturers }
    end
  end

  # GET /espresso_machine_manufacturers/1
  # GET /espresso_machine_manufacturers/1.json
  def show
    @espresso_machine_manufacturer = EspressoMachineManufacturer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @espresso_machine_manufacturer }
    end
  end

  # GET /espresso_machine_manufacturers/new
  # GET /espresso_machine_manufacturers/new.json
  def new
    @espresso_machine_manufacturer = EspressoMachineManufacturer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @espresso_machine_manufacturer }
    end
  end

  # GET /espresso_machine_manufacturers/1/edit
  def edit
    @espresso_machine_manufacturer = EspressoMachineManufacturer.find(params[:id])
  end

  # POST /espresso_machine_manufacturers
  # POST /espresso_machine_manufacturers.json
  def create
    @espresso_machine_manufacturer = EspressoMachineManufacturer.new(params[:espresso_machine_manufacturer])

    respond_to do |format|
      if @espresso_machine_manufacturer.save
        format.html { redirect_to @espresso_machine_manufacturer, :notice => 'Espresso machine manufacturer was successfully created.' }
        format.json { render :json => @espresso_machine_manufacturer, :status => :created, :location => @espresso_machine_manufacturer }
      else
        format.html { render :action => "new" }
        format.json { render :json => @espresso_machine_manufacturer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /espresso_machine_manufacturers/1
  # PUT /espresso_machine_manufacturers/1.json
  def update
    @espresso_machine_manufacturer = EspressoMachineManufacturer.find(params[:id])

    respond_to do |format|
      if @espresso_machine_manufacturer.update_attributes(params[:espresso_machine_manufacturer])
        format.html { redirect_to @espresso_machine_manufacturer, :notice => 'Espresso machine manufacturer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @espresso_machine_manufacturer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /espresso_machine_manufacturers/1
  # DELETE /espresso_machine_manufacturers/1.json
  def destroy
    @espresso_machine_manufacturer = EspressoMachineManufacturer.find(params[:id])
    @espresso_machine_manufacturer.destroy

    respond_to do |format|
      format.html { redirect_to espresso_machine_manufacturers_url }
      format.json { head :no_content }
    end
  end
end

examples/coffeeratings/app/controllers/roasters_controller.rb
class RoastersController < ApplicationController
  # GET /roasters
  # GET /roasters.json
  def index
    @roasters = Roaster.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @roasters }
    end
  end

  # GET /roasters/1
  # GET /roasters/1.json
  def show
    @roaster = Roaster.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @roaster }
    end
  end

  # GET /roasters/new
  # GET /roasters/new.json
  def new
    @roaster = Roaster.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @roaster }
    end
  end

  # GET /roasters/1/edit
  def edit
    @roaster = Roaster.find(params[:id])
  end

  # POST /roasters
  # POST /roasters.json
  def create
    @roaster = Roaster.new(params[:roaster])

    respond_to do |format|
      if @roaster.save
        format.html { redirect_to @roaster, :notice => 'Roaster was successfully created.' }
        format.json { render :json => @roaster, :status => :created, :location => @roaster }
      else
        format.html { render :action => "new" }
        format.json { render :json => @roaster.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /roasters/1
  # PUT /roasters/1.json
  def update
    @roaster = Roaster.find(params[:id])

    respond_to do |format|
      if @roaster.update_attributes(params[:roaster])
        format.html { redirect_to @roaster, :notice => 'Roaster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @roaster.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /roasters/1
  # DELETE /roasters/1.json
  def destroy
    @roaster = Roaster.find(params[:id])
    @roaster.destroy

    respond_to do |format|
      format.html { redirect_to roasters_url }
      format.json { head :no_content }
    end
  end
end

examples/coffeeratings/app/helpers/application_helper.rb
module ApplicationHelper
end

examples/coffeeratings/app/helpers/espresso_machine_manufacturers_helper.rb
module EspressoMachineManufacturersHelper
end

examples/coffeeratings/app/helpers/roasters_helper.rb
module RoastersHelper
end

examples/coffeeratings/app/views/espresso_machine_manufacturers/_form.html.erb
<%= form_for(@espresso_machine_manufacturer) do |f| %>
  <% if @espresso_machine_manufacturer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@espresso_machine_manufacturer.errors.count, "error") %> prohibited this espresso_machine_manufacturer from being saved:</h2>

      <ul>
      <% @espresso_machine_manufacturer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :machine_types %><br />
    <%= f.text_area :machine_types %>
  </div>
  <div class="field">
    <%= f.label :groups %><br />
    <%= f.text_field :groups %>
  </div>
  <div class="field">
    <%= f.label :models %><br />
    <%= f.text_area :models %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

examples/coffeeratings/app/views/espresso_machine_manufacturers/edit.html.erb
<h1>Editing espresso_machine_manufacturer</h1>

<%= render 'form' %>

<%= link_to 'Show', @espresso_machine_manufacturer %> |
<%= link_to 'Back', espresso_machine_manufacturers_path %>

examples/coffeeratings/app/views/espresso_machine_manufacturers/index.html.erb
<h1>Listing espresso_machine_manufacturers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Website</th>
    <th>Machine types</th>
    <th>Groups</th>
    <th>Models</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @espresso_machine_manufacturers.each do |espresso_machine_manufacturer| %>
  <tr>
    <td><%= espresso_machine_manufacturer.name %></td>
    <td><%= espresso_machine_manufacturer.website %></td>
    <td><%= espresso_machine_manufacturer.machine_types %></td>
    <td><%= espresso_machine_manufacturer.groups %></td>
    <td><%= espresso_machine_manufacturer.models %></td>
    <td><%= link_to 'Show', espresso_machine_manufacturer %></td>
    <td><%= link_to 'Edit', edit_espresso_machine_manufacturer_path(espresso_machine_manufacturer) %></td>
    <td><%= link_to 'Destroy', espresso_machine_manufacturer, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Espresso machine manufacturer', new_espresso_machine_manufacturer_path %>

examples/coffeeratings/app/views/espresso_machine_manufacturers/new.html.erb
<h1>New espresso_machine_manufacturer</h1>

<%= render 'form' %>

<%= link_to 'Back', espresso_machine_manufacturers_path %>

examples/coffeeratings/app/views/espresso_machine_manufacturers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @espresso_machine_manufacturer.name %>
</p>

<p>
  <b>Website:</b>
  <%= @espresso_machine_manufacturer.website %>
</p>

<p>
  <b>Machine types:</b>
  <%= @espresso_machine_manufacturer.machine_types %>
</p>

<p>
  <b>Groups:</b>
  <%= @espresso_machine_manufacturer.groups %>
</p>

<p>
  <b>Models:</b>
  <%= @espresso_machine_manufacturer.models %>
</p>


<%= link_to 'Edit', edit_espresso_machine_manufacturer_path(@espresso_machine_manufacturer) %> |
<%= link_to 'Back', espresso_machine_manufacturers_path %>

examples/coffeeratings/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coffeeratings</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

examples/coffeeratings/app/views/roasters/_form.html.erb
<%= form_for(@roaster) do |f| %>
  <% if @roaster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roaster.errors.count, "error") %> prohibited this roaster from being saved:</h2>

      <ul>
      <% @roaster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :blends %><br />
    <%= f.text_area :blends %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

examples/coffeeratings/app/views/roasters/edit.html.erb
<h1>Editing roaster</h1>

<%= render 'form' %>

<%= link_to 'Show', @roaster %> |
<%= link_to 'Back', roasters_path %>

examples/coffeeratings/app/views/roasters/index.html.erb
<h1>Listing roasters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Website</th>
    <th>Blends</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roasters.each do |roaster| %>
  <tr>
    <td><%= roaster.name %></td>
    <td><%= roaster.website %></td>
    <td><%= roaster.blends %></td>
    <td><%= link_to 'Show', roaster %></td>
    <td><%= link_to 'Edit', edit_roaster_path(roaster) %></td>
    <td><%= link_to 'Destroy', roaster, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Roaster', new_roaster_path %>

examples/coffeeratings/app/views/roasters/new.html.erb
<h1>New roaster</h1>

<%= render 'form' %>

<%= link_to 'Back', roasters_path %>

examples/coffeeratings/app/views/roasters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @roaster.name %>
</p>

<p>
  <b>Website:</b>
  <%= @roaster.website %>
</p>

<p>
  <b>Blends:</b>
  <%= @roaster.blends %>
</p>


<%= link_to 'Edit', edit_roaster_path(@roaster) %> |
<%= link_to 'Back', roasters_path %>